//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorny.KetchupCatalog.DaoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ketchup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Producer_ID { get; set; }
        public int Type_ID { get; set; }
        public System.DateTime ManufactureDate { get; set; }
    
        public virtual Producer Producer { get; set; }
    }
}
